export const MOTIVATIONAL_PHRASES: string[] = [
  'Every completed task is a step closer to your goals',
  'Small tasks lead to big achievements',
  "Don't postpone what can be done today",
  'Each task is an opportunity to shine',
  'Success is built task by task',
  'Today is the best day to start working on your dreams',
  'Well-done tasks are the foundation of success',
  'Each task is a step toward a better version of yourself',
  'The key to success lies in the consistency of your daily tasks',
  "Do today what others don't want to, do tomorrow what others can't",
  'Uncompleted tasks are unfulfilled dreams Make them come true!',
  'The reward for a job well done is the opportunity to do another',
  'Tasks are the path to personal and professional progress',
  'Your daily tasks define your path to success',
  'Productivity is the key that unlocks the door to success',
]
